### ISSUE TITLE
The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by AdamLee321** [knoggl/CleanUI#4]
Xcode: Version 14.3 (14E222b)
Mac: Apple M2 Pro MacBook 2023
macOS: 13.3.1 (22E261)

![Screenshot 2023-04-17 at 09 46 40](https://user-images.githubusercontent.com/22890658/232433469-989cda42-593b-44ea-8dd0-0447de5e5466.png)

I have been using this library in my project and was working on a 2018 MacBook pro. Just upgraded to a new MacBook and I am now getting the above error. If anyone knows a fix please let me know. I don't wanna switch all my navigation code.

**Comment by juliangerhards** [comment]
fixed in https://github.com/knoggl/CleanUI/releases/tag/1.9.1
